name: Close App Pull Request

# Fetch email address of user triggering this action
# Trigger manifest repo PR closure (this includes the fetched email address)
# Delete all 'pr-##' images that aren't also tagged as releases

on:
  pull_request:
    types: [ closed ]
    paths: ['**.js', '**.json' , 'public/**', 'views/**', 'Dockerfile']

jobs:
  close-manifest-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Get email associated with Github username
      uses: actions/github-script@v7
      id: get-email
      with: 
        github-token: ${{ github.token }}
        script: |
          return (await github.rest.users.getByUsername({
            username: ${{ tojson(github.actor) }}
          })).data.email;
        result-encoding: string
    - name: Trigger close PR workflow in the manifests repository
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.MANIFEST_PAT }} # Secret auths to manifest repo
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: '${{ github.repository_owner }}',
            repo: 'manifest',
            workflow_id: 'close-pull-request.yaml',
            ref: 'main',
            inputs: {
              actor: '${{ github.actor }}  <${{ steps.get-email.outputs.result }}>',
              head_pr: '${{ github.event.number }}',
              merged: ${{ github.event.pull_request.merged }}
            }
          })
  prune-pr-images:
    runs-on: ubuntu-latest
    steps:
    - name: Prune images for PR-${{ github.event.number }}
      uses: vlaurin/action-ghcr-prune@v0.6.0
      with:
        token: ${{ github.token }}
        organization: ORGNAME
        container: gitops-and-actions
        dry-run: false
        prune-untagged: true
        keep-tags-regexes: |
          ^[0-9]+.[0-9]+.[0-9]+$
        prune-tags-regexes: |
          ^pr-${{ github.event.number }}