namespace: example-app-pr-30
nameSuffix: -pr-30-3fec479
resources:
- ./../../base
images:
- name: app-image
  newName: ghcr.io/ORGNAME/gitops-and-actions
  newTag: pr-30-3fec479
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: example-app-pr-30-3fec479
patches:
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1
